export const SAVE_LOGIN_USER = 'LOGIN_USER';
export const SAVE_WALLET = 'SAVE_WALLET';
export const REQUEST_CURRENCIES = 'REQUEST_CURRENCIES';
export const RECEIVE_CURRENCIES_SUCCESS = 'RECEIVE_CURRENCIES_SUCCESS';
export const RECEIVE_CURRENCIES_ERROR = 'RECEIVE_CURRENCIES_ERROR';
export const SAVE_EXPENSES = 'SAVE_EXPENSES';
export const DELETE_EXPENSES = 'DELETE_EXPENSES';
